name: Moonsea Codex UI

on:
  push:
    branches: ["main"]

jobs:
  Build-React-App:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Configure node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "npm"
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      - name: Build production app
        run: npm run build --if-present
