name: Moonsea Codex UI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: [main]

jobs:
  Build-React-App:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Configure node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Build production app
        run: npm run build --if-present
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: webui-app
          path: build/
          retention-days: 1

  Deploy-To-Server:
    runs-on: ubuntu-latest
    needs: Build-React-App

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: webui-app
      - name: Deploy to Staging server
        uses: easingthemes/ssh-deploy@v2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          SOURCE: "build"
          REMOTE_HOST: ${{ secrets.SERVER }}
          REMOTE_USER: ${{ secrets.USERNAME }}
