# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Moonsea Codex UI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: [main]

jobs:
  Build-React-App:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Configure node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Build production app
        run: npm run build --if-present

      - name: Compress build files
        run: tar -czvf moonsea-codex-webui.tar.gz build/
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: compressed-webui-app
          path: moonsea-codex-webui.tar.gz
          retention-days: 1
